// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpX2pDcLFbRMAVPswEt45RmuQEYkECI5g',
    appId: '1:725374644567:web:8040e66737546fcdefce12',
    messagingSenderId: '725374644567',
    projectId: 'atendimentosamu-c5ba2',
    authDomain: 'atendimentosamu-c5ba2.firebaseapp.com',
    storageBucket: 'atendimentosamu-c5ba2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz6EDJwlpHK4oGKklW_rgH1wC22jm08FU',
    appId: '1:725374644567:android:908d54a80f7be29defce12',
    messagingSenderId: '725374644567',
    projectId: 'atendimentosamu-c5ba2',
    storageBucket: 'atendimentosamu-c5ba2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUc2E-ti2zB7rrwJ0MJGUDYHAwMlQ8lpY',
    appId: '1:725374644567:ios:bb52d00ee4b37c57efce12',
    messagingSenderId: '725374644567',
    projectId: 'atendimentosamu-c5ba2',
    storageBucket: 'atendimentosamu-c5ba2.appspot.com',
    iosBundleId: 'br.com.ipesoft.atendimentoSamuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUc2E-ti2zB7rrwJ0MJGUDYHAwMlQ8lpY',
    appId: '1:725374644567:ios:5c22d73cf042aed1efce12',
    messagingSenderId: '725374644567',
    projectId: 'atendimentosamu-c5ba2',
    storageBucket: 'atendimentosamu-c5ba2.appspot.com',
    iosBundleId: 'com.example.atendimentoSamuApp.RunnerTests',
  );
}
